# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorMessage(object):
    def setupUi(self, ErrorMessage):
        ErrorMessage.setObjectName("ErrorMessage")
        ErrorMessage.resize(350, 105)
        icon=QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("error.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        ErrorMessage.setWindowIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ErrorMessage.sizePolicy().hasHeightForWidth())
        ErrorMessage.setSizePolicy(sizePolicy)
        ErrorMessage.setMaximumSize(QtCore.QSize(350, 180))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        ErrorMessage.setFont(font)
        ErrorMessage.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"font: 75 10pt \"Comic Sans MS\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(ErrorMessage)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Image = QtWidgets.QLabel(ErrorMessage)
        self.Image.setMaximumSize(QtCore.QSize(30, 30))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("close.png"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.horizontalLayout.addWidget(self.Image)
        self.ErrorMessageLabel = QtWidgets.QLabel(ErrorMessage)
        self.ErrorMessageLabel.setObjectName("ErrorMessageLabel")
        self.horizontalLayout.addWidget(self.ErrorMessageLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Button_ok = QtWidgets.QPushButton(ErrorMessage)
        self.Button_ok.setStyleSheet("border:1px solid black ;\n"
"padding:2px 20px 2px 20px;")
        self.Button_ok.setObjectName("Button_ok")
        self.horizontalLayout_2.addWidget(self.Button_ok)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.Button_ok.clicked.connect(lambda:ErrorMessage.close())
        self.retranslateUi(ErrorMessage)
        QtCore.QMetaObject.connectSlotsByName(ErrorMessage)

    def retranslateUi(self, ErrorMessage):
        _translate = QtCore.QCoreApplication.translate
        ErrorMessage.setWindowTitle(_translate("ErrorMessage", "ERROR"))
        self.ErrorMessageLabel.setText(_translate("ErrorMessage", "Error Message"))
        self.Button_ok.setText(_translate("ErrorMessage", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErrorMessage = QtWidgets.QDialog()
    ui = Ui_ErrorMessage()
    ui.setupUi(ErrorMessage)
    ErrorMessage.show()
    sys.exit(app.exec_())
